//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AistTrader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
       
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Common.Settings.SettingsArrayList Agents {
            get {
                return ((global::Common.Settings.SettingsArrayList)(this["Agents"]));
            }
            set {
                this["Agents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Common.Settings.SettingsArrayList AgentConnection {
            get {
                return ((global::Common.Settings.SettingsArrayList)(this["AgentConnection"]));
            }
            set {
                this["AgentConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Common.Settings.SettingsArrayList AgentPortfolio {
            get {
                return ((global::Common.Settings.SettingsArrayList)(this["AgentPortfolio"]));
            }
            set {
                this["AgentPortfolio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Common.Settings.SettingsArrayList AgentManager {
            get {
                return ((global::Common.Settings.SettingsArrayList)(this["AgentManager"]));
            }
            set {
                this["AgentManager"] = value;
            }
        }
       
    }
}
